{
 "title": "SeaweedFS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values({namespace=\"drycc\"},service)"
    }
   },
   {
    "name": "method",
    "label": "method",
    "query": {
     "query": "label_values(SeaweedFS_s3_request_total{namespace=\"drycc\"},type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "S3 api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "S3 QPS by statusCode",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(SeaweedFS_s3_request_total{namespace=\"drycc\", service=~\"$service\",type=~\"$method\"}[2m])) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "S3 QPS by  method",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(SeaweedFS_s3_request_total{namespace=\"drycc\",service=~\"$service\"}[2m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "S3 Request Duration 80th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=\"drycc\",service=~\"$service\"}[2m])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=\"drycc\",service=~\"$service\",type=~\"$method\"}[2m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "S3 Request Duration 95th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=\"drycc\",service=~\"$service\"}[2m])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=\"drycc\",service=~\"$service\", type=~\"$method\"}[2m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "S3 Request Duration 99th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=\"drycc\",service=~\"$service\"}[2m])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=\"drycc\",service=~\"$service\", type=~\"$method\"}[2m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Volume Server Request Duration 99th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_volumeServer_request_seconds_bucket{namespace=\"drycc\",service=~\"$service\"}[2m])) by (le, exported_instance))",
       "legendFormat": "{{exported_instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_volumeServer_request_seconds_bucket{namespace=\"drycc\",service=~\"$service\"}[2m])) by (le))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Volume Server QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(SeaweedFS_volumeServer_request_total{namespace=\"drycc\",service=~\"$service\"}[2m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Volume Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(SeaweedFS_volumeServer_volumes{namespace=\"drycc\",service=~\"$service\"}) by (collection, type)",
       "legendFormat": "{{collection}} {{type}}"
      },
      {
       "expr": "sum(max(SeaweedFS_volumeServer_max_volumes{namespace=\"drycc\",service=~\"$service\"}) by (pod))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(max(SeaweedFS_volumeServer_read_only_volumes{namespace=\"drycc\",service=~\"$service\"}) by (pod))",
       "legendFormat": "Read only"
      }
     ]
    },
    {
     "title": "Used Disk Space by Collection and Type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(SeaweedFS_volumeServer_total_disk_size{namespace=\"drycc\",service=~\"$service\"}) by (collection, type)",
       "legendFormat": "{{collection}} {{type}}"
      }
     ]
    },
    {
     "title": "Used Disk Space by Host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(max(SeaweedFS_volumeServer_total_disk_size{namespace=\"drycc\",service=~\"$service\"}) by (collection,pod)) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Filer QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(SeaweedFS_filer_request_total{namespace=\"drycc\",service=~\"$service\"}[2m])",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filer Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Filer Store Request Duration 99th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filerStore_request_seconds_bucket{namespace=\"drycc\",service=~\"$service\"}[2m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Filer Store QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(SeaweedFS_filerStore_request_total{namespace=\"drycc\",service=~\"$service\"}[2m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filer Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Filer Go Memory Stats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{namespace=~\"drycc\", service=~\"$service\"}",
       "legendFormat": "bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"drycc\", service=~\"$service\"}[30s])",
       "legendFormat": "alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=~\"drycc\", service=~\"$service\"}",
       "legendFormat": "stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=~\"drycc\", service=~\"$service\"}",
       "legendFormat": "heap inuse"
      }
     ]
    },
    {
     "title": "Filer Go GC duration quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=~\"drycc\", service=~\"$service\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Filer Go Routines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{namespace=~\"drycc\", service=~\"$service\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}