{
 "title": "Influx",
 "tags": [ "drycc" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Number of Measurements",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"influxdata/influxdb/schema\"\nschema.measurements(bucket: v.bucket)\n|> count()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful Task Runs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influxdb_shard",
     "query": "import \"csv\"\n\ndummy_data = \"#group,false,false,false,false,true,true,true,true\n#datatype,string,long,dateTime:RFC3339,double,string,string,string,string\n#default,_result,,,,,,,\n,result,table,_time,_value,_field,_measurement,status,task_type\n,,0,2000-01-01T00:00:00.000000Z,0,counter,task_executor_total_runs_complete,success,system\"\n\ndefault = csv.from(csv: dummy_data)\n\nnew = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"task_executor_total_runs_complete\")\n  |> filter(fn: (r) => r.status == \"success\")\n  |> filter(fn: (r) => r.task_type == \"system\")\n  |> filter(fn: (r) => r._field == \"counter\")\n  |> last()\n\nunion(tables: [default, new]) |> last()",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Share Disk Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "$tag_pod_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_shard_disk_size\")\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "$tag_pod_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_buckets_total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"counter\")\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Local Object Store IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "$tag_pod_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"boltdb_reads_total\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> drop(columns: [\"url\", \"_field\", \"_measurement\"])"
    }
   ]
  }
 ]
}