{
 "title": "TiKV",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tikv_engine_size_bytes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> keyValues(keyColumns: [\"_value\"])\n  |> duplicate(column: \"url\", as: \"_value\")\n  |> group() \n  |> keep(columns: [\"_value\"])\n  "
   },
   {
    "name": "db",
    "label": "db",
    "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tikv_engine_block_cache_size_bytes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> keyValues(keyColumns: [\"_value\"])\n  |> duplicate(column: \"db\", as: \"_value\")\n  |> group() \n  |> keep(columns: [\"_value\"])\n  "
   },
   {
    "name": "command",
    "label": "command",
    "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tikv_storage_command_total\")\n  |> duplicate(column: \"type\", as: \"_value\")\n  |> keyValues(keyColumns: [\"_value\"])\n  |> group() \n  |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Leader",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "legendFormat": "scheduler-{{instance}}",
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tikv_raftstore_region_count\")\n  |> filter(fn: (r) => r[\"type\"] == \"leader\")\n  |> keep(columns: [\"_time\", \"url\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n  |> keep(columns: [\"_time\", \"url\", \"value\"])"
    },
    {
     "legendFormat": "channelfull-{{instance}}-{{type}}"
    },
    { "legendFormat": "coprocessor-{{instance}}" },
    { "legendFormat": "stall-{{instance}}" }
   ]
  },
  {
   "title": "Startup datetime",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_start_time_seconds\")\n  |> filter(fn: (r) => r[\"url\"] =~ /tikv/)\n  |> toInt()\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> duplicate(column: \"url\", as: \"_time\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "The QPS of different kinds of commands in each TiKV instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tikv_grpc_msg_duration_seconds\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"type\"] != \"kv_gc\")\n  |> filter(fn: (r) => r[\"url\"] == \"${instance}\")\n  |> keep(columns: [\"_time\", \"_value\", \"type\", \"url\"])\n  |> derivative(unit: 1s)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Store size",
   "type": "timeseries",
   "description": "The storage size per TiKV instance",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "legendFormat": "scheduler-{{instance}}",
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tikv_store_size_bytes\")\n  |> filter(fn: (r) => r[\"type\"] == \"used\")\n  |> keep(columns: [\"_time\", \"url\", \"_value\"])\n  |> group(columns: [\"_time\", \"url\"], mode:\"by\")\n  |> cumulativeSum(columns: [\"_value\", \"url\"])\n  |> last()\n  |> group(columns: [\"url\"], mode:\"by\")\n"
    },
    {
     "legendFormat": "channelfull-{{instance}}-{{type}}"
    },
    { "legendFormat": "coprocessor-{{instance}}" },
    { "legendFormat": "stall-{{instance}}" }
   ]
  },
  {
   "title": "Available size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "legendFormat": "scheduler-{{instance}}",
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tikv_store_size_bytes\")\n  |> filter(fn: (r) => r[\"type\"] == \"available\")\n  |> keep(columns: [\"_time\", \"url\", \"_value\"])\n  |> group(columns: [\"_time\", \"url\"], mode:\"by\")\n  |> cumulativeSum(columns: [\"_value\", \"url\"])\n  |> last()\n  |> group(columns: [\"url\"], mode:\"by\")\n"
    },
    {
     "legendFormat": "channelfull-{{instance}}-{{type}}"
    },
    { "legendFormat": "coprocessor-{{instance}}" },
    { "legendFormat": "stall-{{instance}}" }
   ]
  },
  {
   "title": "Capacity size",
   "type": "timeseries",
   "description": "The storage size per TiKV instance",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "legendFormat": "scheduler-{{instance}}",
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tikv_store_size_bytes\")\n  |> filter(fn: (r) => r[\"type\"] == \"capacity\")\n  |> keep(columns: [\"_time\", \"url\", \"_value\"])\n  |> group(columns: [\"_time\", \"url\"], mode:\"by\")\n  |> cumulativeSum(columns: [\"_value\", \"url\"])\n  |> last()\n  |> group(columns: [\"url\"], mode:\"by\")\n"
    },
    {
     "legendFormat": "channelfull-{{instance}}-{{type}}"
    },
    { "legendFormat": "coprocessor-{{instance}}" },
    { "legendFormat": "stall-{{instance}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "milli-cores" } },
   "targets": [
    {
     "legendFormat": "scheduler-{{instance}}",
     "query": "from(bucket: \"kubernetes\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_cpu_seconds_total\")\n  |> filter(fn: (r) => r[\"url\"] =~ /tikv/)\n  |> toInt()\n  |> map(fn: (r) => ({ r with _value: r._value / 1000 }))\n  |> keep(columns: [\"_time\", \"_value\", \"url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n  "
    },
    {
     "legendFormat": "channelfull-{{instance}}-{{type}}"
    },
    { "legendFormat": "coprocessor-{{instance}}" },
    { "legendFormat": "stall-{{instance}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "legendFormat": "scheduler-{{instance}}",
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_resident_memory_bytes\")\n  |> filter(fn: (r) => r[\"url\"] =~ /tikv/)\n  |> keep(columns: [\"_time\", \"_value\", \"url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "legendFormat": "channelfull-{{instance}}-{{type}}"
    },
    { "legendFormat": "coprocessor-{{instance}}" },
    { "legendFormat": "stall-{{instance}}" }
   ]
  }
 ]
}